### PR TITLE
Fix: use native base64 decode and strip newlines

### LINKED ISSUE #11: No or fractured images / base64 decode problem.
Seems like base64 decoding have issue with new lines in encoded body like this:

```
------MultipartBoundary--O7kVRKVfmd1nCNuKBaQmK8j3jZ9Bb9MhcZjFQGEJ91----
Content-Type: image/png
Content-Transfer-Encoding: base64
Content-Location: http://aurora24.ru/bitrix/images/aspro.next/themes/mobile_menu1.png

iVBORw0KGgoAAAANSUhEUgAAAIoAAABxCAMAAAA9DMuMAAAABGdBTUEAALGPC/xhBQAAAAFzUkdC
AK7OHOkAAAERUExUReLi4tDQ0N3d3dbW1tLS0svLy9ra2v///+Xl5ePj487OzuTk5L29verq6tnZ
2fz8/MfHx+Dg4MHBwevr69PT0+bm5mVlZff395GRkdTU1PHx8cTExD8/P2NjYzo6OsbGxs/Pz97e
...
```

Simplest solution is to replace the decoder with classic one, with new line removing.

https://github.com/testimio/mhtml-parser/blob/master/src/decoder.js#L6

```
return Buffer.from(body.toString().replace(/\r|\n/g, ''), 'base64');
```

### PR DESCRIPTION
**Pull request by javamonn**
### I am proposing this change because:

This resolves #11.

Checklist:
 - [ ] tests were added for new features
 - [x] tests and lint pass
 - [ ] benchmark ran

### CODE REVIEW

**Comment by benjamingr** [comment]
Thanks, this introduces a regression in the benchmarks but I think it's worth the tradeoff for correctness + 64 doesn't seem maintained.

**Comment by benjamingr** [comment]
FWIW I think the reason this happened is that NPM started installing `peerDependency`s by default since 64 was an optional dependency for a while

**Comment by benjamingr** [comment]
So, since I no longer work with Testim.io - I don't have write access here. I've contacted some friends still in Testim and they'll give me write access and merge this. This means it'll probably take a day or two more to merge - sorry for the inconvenience!

If this is urgent I am willing to publish a version with this patch without merging but I strongly prefer to wait so the source code matches what people get on NPM.

**Comment by javamonn** [comment]
@benjamingr Yes, I observed the same behavior with the `optionalDependencies` getting installed by default - I wonder if behavior with `npm install --production` would be different. 

I'm pretty sure I double-checked the native parser as-is as well. The important part of the fix is stripping newlines (not the decoder we use) so we could look at performance impact of continuing to use `64` while still doing the regexp replace.

No rush on the timing and thanks for the heads up - i'm depending on the branch on my fork directly at the moment, and I can switch back once the new version is published.

**Pull request merged**
